### ISSUE TITLE
Click should remove selected location

### ISSUE THREAD

**Issue by SrihariThalla** [benjamintd/mapbox-maps#26]
Either a left click or a right click is not removing the selected location!

### Reproduce

1. Select a place from the search or use right click and select the coordinate
2. The location will be selected
3. Clicking on any other area should ideally remove the selected location - from the search and the marker.

Here is using right click:
![screenshot 2017-05-25 16 16 56](https://cloud.githubusercontent.com/assets/7479937/26447421/235e6d30-4166-11e7-8e74-49d8dedec887.png)

One possible use for keeping the selection is to use it in directions: `from` or `to`. But we are not really used to this behaviour?

**Comment by benjamintd** [comment]
Hey Srihari, you're right, currently the only option to remove that marker is to click on the closing button in the search bar.

It seems from browsing other interfaces that the expected behavior is to quit the search mode on click anywhere on the map; this can be added in [here](https://github.com/benjamintd/mapbox-maps/blob/master/src/components/Map.js#L237-L266) doing something like [this](https://github.com/benjamintd/mapbox-maps/blob/master/src/components/Map.js#L206-L207).

I think we only want a _left_ click to trigger removing the search place.

cc/ @SrihariThalla
