### ISSUE TITLE
Development mode and settings

### ISSUE THREAD

**Issue by mpmckenna8** [benjamintd/mapbox-maps#45]
I find it helpful to have a dev mode in these redux, react apps with some extra logging and stuff to help figure out what's going on.  I especially like redux-logger for figuring out all the actions that are firing as I first checkout how the app is working.  See https://github.com/mpmckenna8/mapbox-maps/blob/action_logger/src/index.js#L34 for an example and let me know if it would be wanted to pull request or if there's a better way to do it or if you think this isn't necessary.

**Comment by benjamintd** [comment]
I'm personally using the [Redux DevTools Chrome extension](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en), which seems to cover the same use case as redux logger?

It should be working out of the box without having to add anything in the app's code.

Thanks for the suggestion, if there's some strong reasons to switch to redux-logger I can consider integrating that? Otherwise I'm pretty happy with DevTools at the moment.

**Comment by SrihariThalla** [comment]
@mpmckenna8 Redux DevTools extension is indeed good. You might want to check it out. As @benjamintd said, there is no extra piece of code necessary to review Redux.

May I ask what are the benefits of redux-logger over Redux DevTools? (I have never used redux-logger.)

**Comment by mpmckenna8** [comment]
Cool, wasn't using Redux DevTools and get rid of extra middleware then.  Thanks for the suggestion. I guess redux-logger would be nice for people who want to develop with Firefox, but I'm still stuck in chrome land so it doesn't really matter.
